name: Deploy to Namecheap via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Deploy Files via FTP
        run: |
          lftp -e "
          set ftp:ssl-allow no;
          open -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }} -p ${{ secrets.FTP_PORT }} ${{ secrets.FTP_SERVER }};
          mirror -R --delete --parallel=5 ./ /public_html/;
          bye
          "
