name: Deploy Laravel to cPanel via FTP

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3  # Change this to match your Laravel version
          extensions: mbstring, xml, ctype, json, pdo, openssl, tokenizer, fileinfo

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Set Laravel Permissions
        run: |
          chmod -R 755 storage bootstrap/cache
          chmod -R 777 storage bootstrap/cache

      # Debug FTP Connection First
      - name: Test FTP Connection (Optional)
        run: |
          echo "Testing FTP Connection..."
          curl -v --ssl -k --user "${{ secrets.FTP_USER }}:${{ secrets.FTP_PASSWORD }}" "ftp://${{ secrets.FTP_SERVER }}:${{ secrets.FTP_PORT }}/"

      # Upload via FTP (Use FTPES for encrypted connection)
      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftpes  # Use FTPES (explicit SSL mode)
          server-dir: /public_html/  # Update to match your cPanel setup
          local-dir: ./
          timeout: 300000  # Increase timeout to 5 minutes
          log-level: verbose  # Enable debugging logs

      - name: Run Migrations (Optional)
        run: php artisan migrate --force
        env:
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Clear Cache
        run: php artisan config:cache
